name: VehicleBuilder
description: "This is a Display Entity-based vehicle system that allows all players in a vanilla environment to experience high-quality vehicles without using any resource packs."
author: Srain3
website: "https://github.com/Srain3/VehicleBuilder"
main: com.github.srain3.vehiclebuilder.VehicleBuilder
version: "${version}"
api-version: "1.21"

commands:
  vbmenu:
    description: "VehicleBuilder main menu command."
    permission: vehiclebuilder.command.vbmenu

permissions:
  vehiclebuilder.command.vbmenu:
    description: "VehicleBuilder main menu permission."
    default: true
